// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPGa-N7g9Ugz_lqCm95GwLNRxjOz6EbFg',
    appId: '1:773783945856:web:04f3f44f4a66ce4c6f1c65',
    messagingSenderId: '773783945856',
    projectId: 'yulin-hackathon',
    authDomain: 'yulin-hackathon.firebaseapp.com',
    storageBucket: 'yulin-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1wmgVnythug5pexKkRxSUl2a0hPOPqA',
    appId: '1:773783945856:android:531b0c3a934f3cfd6f1c65',
    messagingSenderId: '773783945856',
    projectId: 'yulin-hackathon',
    storageBucket: 'yulin-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyV5KVBbpMQmOKVX3N_vdHCBuz7rvfkOo',
    appId: '1:773783945856:ios:c760874107aca5796f1c65',
    messagingSenderId: '773783945856',
    projectId: 'yulin-hackathon',
    storageBucket: 'yulin-hackathon.firebasestorage.app',
    androidClientId: '773783945856-1njo2i6dl3jr1rpdvee87lk4e21v0neg.apps.googleusercontent.com',
    iosClientId: '773783945856-bcpo8ov5ij0ghe2mkfrruj598543pqmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyV5KVBbpMQmOKVX3N_vdHCBuz7rvfkOo',
    appId: '1:773783945856:ios:c760874107aca5796f1c65',
    messagingSenderId: '773783945856',
    projectId: 'yulin-hackathon',
    storageBucket: 'yulin-hackathon.firebasestorage.app',
    androidClientId: '773783945856-1njo2i6dl3jr1rpdvee87lk4e21v0neg.apps.googleusercontent.com',
    iosClientId: '773783945856-bcpo8ov5ij0ghe2mkfrruj598543pqmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPGa-N7g9Ugz_lqCm95GwLNRxjOz6EbFg',
    appId: '1:773783945856:web:e3b7d034136b83186f1c65',
    messagingSenderId: '773783945856',
    projectId: 'yulin-hackathon',
    authDomain: 'yulin-hackathon.firebaseapp.com',
    storageBucket: 'yulin-hackathon.firebasestorage.app',
  );

}