// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxbIQmlnT2Fg9WagxL7MR1YfM6fNyv3_8',
    appId: '1:300035777622:web:bfde7771debbee2672c7f7',
    messagingSenderId: '300035777622',
    projectId: 'exercise8-f777e',
    authDomain: 'exercise8-f777e.firebaseapp.com',
    storageBucket: 'exercise8-f777e.firebasestorage.app',
    measurementId: 'G-TJWM7M5PJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3IFOyWE2r5YoiulFbLFIYrUL2o-77FnA',
    appId: '1:300035777622:android:f9329b97088178e872c7f7',
    messagingSenderId: '300035777622',
    projectId: 'exercise8-f777e',
    storageBucket: 'exercise8-f777e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGKjkEFbt6xZ7SanXD76ZKraOTl7BZP8o',
    appId: '1:300035777622:ios:b1fc1da11250587272c7f7',
    messagingSenderId: '300035777622',
    projectId: 'exercise8-f777e',
    storageBucket: 'exercise8-f777e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGKjkEFbt6xZ7SanXD76ZKraOTl7BZP8o',
    appId: '1:300035777622:ios:b1fc1da11250587272c7f7',
    messagingSenderId: '300035777622',
    projectId: 'exercise8-f777e',
    storageBucket: 'exercise8-f777e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxbIQmlnT2Fg9WagxL7MR1YfM6fNyv3_8',
    appId: '1:300035777622:web:d30ba56b89fc44bb72c7f7',
    messagingSenderId: '300035777622',
    projectId: 'exercise8-f777e',
    authDomain: 'exercise8-f777e.firebaseapp.com',
    storageBucket: 'exercise8-f777e.firebasestorage.app',
    measurementId: 'G-0GBWLD0K97',
  );
}
